version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      ruby-dependencies:
        patterns:
          - "*"
        applies-to: "security-updates"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: "increase"
